name: Rust CI & Auto Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  WORKING_DIRECTORY: id_generator_service

jobs:
  check-and-test:
    name: Check and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ${{ env.WORKING_DIRECTORY }}
      - name: Run tests
        run: cargo test
        working-directory: ${{ env.WORKING_DIRECTORY }}

  release:
      name: Release for ${{ matrix.os }}
      needs: check-and-test
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      strategy:
        matrix:
          include:
            - os: ubuntu-latest
              artifact_name: id_generator_linux
              asset_name: id_generator_service_linux
            - os: windows-latest
              artifact_name: id_generator_service.exe
              asset_name: id_generator_service_windows.exe
            - os: macos-latest
              artifact_name: id_generator_service
              asset_name: id_generator_service_macos
  
      runs-on: ${{ matrix.os }}
      permissions:
        contents: write
  
      steps:
        - uses: actions/checkout@v4
        - name: Install Rust
          uses: dtolnay/rust-toolchain@stable
  
        - name: Build Release
          run: cargo build --release
          working-directory: ${{ env.WORKING_DIRECTORY }}
  
        - name: Upload to Release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: v0.1.0 # 这里建议配合前面的自动获取版本逻辑
            files: |
              ${{ env.WORKING_DIRECTORY }}/target/release/${{ matrix.artifact_name }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
